### ISSUE TITLE
07_04_random_forest in baseball_fantasy

### ISSUE THREAD

**Issue by AntoineLB13** [nathanbraun/ltcwbb-files#1]
Hello nathan,
in 07_04_random_forest, I am experiencing problems.
First of all, the DATA100 line does not take all the necessary directories into account. It is './data/100-game-sample/' instead of starting at the directory of Users/.
and, the line dfp = (pd.read_csv(path.join(DATA100, 'pitches.csv'))
       .query("pitch_type.notnull() & pitch_type not in ('FO', 'PO')")) has an error to it: TypeError: unhashable type: 'numpy.ndarray'
I tried to fix it but I am no pro.
Wondering if you can tell me why it does not work like all the other files of every other chapter.

Great book by the way

**Comment by nathanbraun** [comment]
Thanks for letting me know about this.  I just updated the `DATA100` directory in that file to be more consistent with the rest of the files, you can try grabbing them again.

As for me, the line you reference:

```python
dfp = (pd.read_csv(path.join(DATA100, 'pitches.csv'))
.query("pitch_type.notnull() & pitch_type not in ('FO', 'PO')")
```

works (I even copied and pasted what you had here), so not sure what's going on.  Maybe try it with the updated `DATA100` and let me know if it still doesn't work?

**Comment by AntoineLB13** [comment]
Ok thanks
This is what I used instead and I believe it works
dfp = (pd.read_csv(path.join(DATA100, 'pitches.csv'))
       .query("pitch_type not in ('FO', 'PO')"))
dfp = dfp.loc[dfp['pitch_type'].notnull()]

I am getting around 85-86 % when I run the test['correct'].mean()

**Comment by nathanbraun** [comment]
Sometimes you can also specify `engine='python'` too.  Like:

```python
dfp = (pd.read_csv(path.join(DATA100, 'pitches.csv'))
.query("pitch_type.notnull() & pitch_type not in ('FO', 'PO')", engine='python')
```

But glad it's working now.

**Comment by AntoineLB13** [comment]
Hello, for the web scraping section, I feel like it only works for your
specific baseball-almanac webpage and not for anything else. Do you have
other examples of web scraping on other sites to make us understand more
the web scraping of various html setups of websites?
Thank you and have a good day
