### ISSUE TITLE
Chapter 1 and Granularity

### ISSUE THREAD

**Issue by jaydeflix** [nathanbraun/ltcwbb-files#2]
Just leaving a little editorial feedback on the book itself. 

While you describe granularity as part of the Example Datasets section, you never actually define it, you simply refer to it as 'what level is this data at.' The first mention of granularity is in the first question of the End of Chapter exercises. This could be confusing to readers who don't know the term or how it would be applied to the data. 

If you make a revised edition, I'd look to put in a definition of granularity somewhere before the question.

**Comment by nathanbraun** [comment]
Thanks @jaydeflix, just pushed a new version of the book (and updated the change log here) taking care of this.
