### ISSUE TITLE
Host lookup-service-prod.mlb.com/json/X no longer works

### ISSUE THREAD

**Issue by lozdog245** [nathanbraun/ltcwbb-files#3]
Hi there @nathanbraun ,

When attempting to do exercises involving the above MLB API resource, it looks like it no longer works. How can I complete these exercises starting from "MLB Data API Example" on page 148 onwards?  

Thanks

**Comment by nathanbraun** [comment]
Hi @lozdog245, thanks for letting me know about this — I'll take a look this week.

**Comment by nathanbraun** [comment]
Just fixed this -- see release notes. Ended up using a different (though still official apparently) API route and adding a section on the MLBStats-API package.  Try it out and let me know what you think!

**Comment by lozdog245** [comment]
Hi Nathan, 

Thank you for updating the code. I tried it out and it works now.
